site_name: Scikit-garden
site_description: 'Documentation for scikit-garden'
pages:
  - Home: index.md
  - API Reference: api.md
  - Trees: trees/about.md
  - Ensembles: ensembles/about.md
theme: readthedocs
